USE data_analytics;
#Q1
SELECT Product,
       SUM(Quantity) AS Total_Quantity
FROM dataset3
GROUP BY Product
ORDER BY Total_Quantity DESC
LIMIT 1;
#answer#product sold the highest quantity is Chair=562 . 
#Q2
SELECT PaymentMethod,
       COUNT(OrderID) AS Total_Orders
FROM dataset3
GROUP BY PaymentMethod
ORDER BY Total_Orders DESC
LIMIT 1;
#Answer# Most Used payment method=Online . 
#Q3
SELECT OrderID,
       CustomerID,
       Product,
       TotalPrice
FROM dataset3
ORDER BY TotalPrice DESC
LIMIT 3;
#Answer# Top 3 highest order value =tablet, monitor, laptops .
#Q4
SELECT ShippingAddress,
       SUM(TotalPrice) AS Total_Revenue
FROM dataset3
GROUP BY ShippingAddress
ORDER BY Total_Revenue DESC
LIMIT 1;
#Answer# The shipping address that generated the highest revenue is 533 Main St,
# with total sales of 7753.73.
#Q5
SELECT CustomerID,
       SUM(TotalPrice) AS Total_Spent
FROM dataset3
GROUP BY CustomerID
ORDER BY Total_Spent DESC
LIMIT 1;
#Answer# customer that spent the most money = 7753.73 .
#Q6
SELECT OrderStatus,
       COUNT(OrderID) AS Total_Orders
FROM dataset3
GROUP BY OrderStatus
limit 5;
#Answer# Count the number of orders for each order status.
#Q7
SELECT PaymentMethod,
       AVG(TotalPrice) AS Average_Order_Value
FROM dataset3
GROUP BY PaymentMethod
ORDER BY Average_Order_Value DESC;
#Answer# The average order value for each payment method.
#Q8
SELECT Product,
       SUM(TotalPrice) AS Total_Sales
FROM dataset3
GROUP BY Product
ORDER BY Total_Sales DESC;
#Answer# Total sales generated by each product.
#Q9
SELECT ReferralSource,
       SUM(TotalPrice) AS Revenue
FROM dataset3
GROUP BY ReferralSource
ORDER BY Revenue DESC
LIMIT 1;
#Answer# Referral source generated the highest revenue = 'Instagram', '275285.45'
#10
SELECT CustomerID,
       SUM(Quantity) AS Total_Items
FROM dataset3
GROUP BY CustomerID
HAVING SUM(Quantity) > 5
ORDER BY Total_Items DESC;
#Answer# Which customers purchased more than five items?
#11
SELECT *
FROM dataset3
WHERE OrderStatus = 'Completed';
#Answer#Display all completed orders.
#Q12
SELECT *
FROM dataset3
WHERE TotalPrice > 500
ORDER BY TotalPrice DESC;
#Answer# where the total price is greater than 1000 = N0
#13
SELECT *
FROM dataset3
WHERE PaymentMethod = 'Credit Card';
#Answer# All the orders paid using Credit Card.
#Q14
SELECT *
FROM dataset3
WHERE CouponCode IS NOT NULL
AND CouponCode <> '';
#Answer# Customers who used a coupon code.
#Q15
SELECT *
FROM dataset3
ORDER BY Date DESC
LIMIT 5;
#Answer# Five most recent orders